AllCops:
  Includes:
    - Rakefile
    - config.ru
  Excludes:
    - script/**
    - vendor/**
    - bin/**
    - examples/**
    - gemfiles/**
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
Blocks:
  Enabled: false
AlignParameters:
  Enabled: false
HashSyntax:
  EnforcedStyle: ruby19