language: ruby
rvm:
  - ruby-head
  - jruby-head
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - rbx-19mode
  - jruby-19mode
# gemfile:
#   - gemfiles/Gemfile.middleman-3.1.x
#   - gemfiles/Gemfile.rails-3.2.x
#   - Gemfile
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-19mode
    - rvm: jruby-19mode
notifications:
  email: false
