language: ruby
cache: bundler
bundler_args: --without development
rvm:
  - ruby-head
  - jruby-head
  - rbx-head
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - rbx
  - jruby
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-head
    - rvm: rbx
    - rvm: jruby
notifications:
  email: false