bundler_args: --without development
language: ruby
rvm:
  - rbx-19mode
  - jruby-19mode
  - 1.9.2
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/Gemfile.middleman-3.1.x
  - gemfiles/Gemfile.rails-3.2.x
  - Gemfile
matrix:
  allow_failures:
    - rvm: rbx-19mode