defaults: &defaults
  fog_provider: "AWS"
  aws_access_key_id: "AKIAI6IOHCMYYPNEJ6VQ"
  aws_secret_access_key: "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"
  region: "us-east-1"
  run_on_precompile: true

development:
  <<: *defaults
  fog_directory: "multi-sync-rails-4"
  existing_remote_files: keep

test:
  <<: *defaults
  fog_directory: "multi-sync-rails-4"
  existing_remote_files: keep

production:
  <<: *defaults
  fog_directory: "multi-sync-rails-4"
  existing_remote_files: delete
